# Generated by Django 4.2.5 on 2023-09-14 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_alter_usuario_email_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
