# Generated by Django 4.2.5 on 2023-09-14 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MovieApp', '0005_reseña_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='deseados',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ListaDeseados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peliculas', models.ManyToManyField(to='MovieApp.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
