# Generated by Django 4.2.5 on 2023-09-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0007_rename_listadeseados_favoritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='deseados',
            new_name='favs',
        ),
    ]
