# Generated by Django 4.2.5 on 2023-09-15 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MovieApp', '0008_rename_deseados_pelicula_favs'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='peliculas_favoritas',
            field=models.ManyToManyField(to='MovieApp.pelicula'),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
