# Generated by Django 4.2.5 on 2023-09-15 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0009_usuario_peliculas_favoritas_alter_favoritos_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritos',
            old_name='peliculas',
            new_name='pelicula',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='peliculas_favoritas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='lista_favoritos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieApp.favoritos'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
