# Generated by Django 4.2.5 on 2023-09-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0010_rename_peliculas_favoritos_pelicula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='lista_favoritos',
        ),
        migrations.AddField(
            model_name='favoritos',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieApp.usuario'),
        ),
    ]
