# Generated by Django 4.2.5 on 2023-09-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0011_remove_usuario_lista_favoritos_favoritos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(to='MovieApp.pelicula'),
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
    ]
